### ISSUE TITLE
滑动冲突

### ISSUE THREAD

**Issue by skyhzx** [brucezz/CardStackView#1]
请问如果在最外层加scrollview ，会产生滑动冲突，若在fragment中使用，应该怎么解决呢？

**Comment by bruce3x** [comment]
emmmm... 这个项目已经很久没有维护了。
这个 View 的手势交互是依赖于 `onTouchEvent` 的，如果它的父 View 消费掉事件，就没法正常工作了。
你可以考虑在父 View 中手动分发事件，或者在子 View 触发手势之后，调用 `requestDisallowInterceptTouchEvent` 防止父 View 拦截。
